"""Apple GPU Runtime - Unified API for GPU operations on Apple Silicon."""

from applegpu_runtime.applegpu_runtime import (
    GpuTensor,
    version,
    init_backend,
    device_name,
    dtype_size,
    tensor,
    eval,
    to_list,
    shape,
    destroy,
    set_limits,
    memory_usage,
    tensor_count,
    add,
    sub,
    mul,
    div,
    neg,
    relu,
    exp,
    log,
    sqrt,
    softmax,
    transpose,
    attention,
    matmul,
)

__version__ = version()
__all__ = [
    "GpuTensor",
    "version",
    "init_backend",
    "device_name",
    "dtype_size",
    "tensor",
    "eval",
    "to_list",
    "shape",
    "destroy",
    "set_limits",
    "memory_usage",
    "tensor_count",
    "add",
    "sub",
    "mul",
    "div",
    "neg",
    "relu",
    "exp",
    "log",
    "sqrt",
    "softmax",
    "transpose",
    "attention",
    "matmul",
]
